spring.application.name=TaskManagerbackend


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/taksManager
spring.datasource.username=postgres
spring.datasource.password=root
